export const ADD_HABIT = "ADD_HABIT";

export const AUTH_CONFIRM = "AUTH_CONFIRM";

export const AUTH_REQUEST = "AUTH_REQUEST";

export const AUTH_REVOKE = "AUTH_REVOKE";

export const CREATE_STACK = "CREATE_STACK";

export const CREATE_STACK_CANCEL = "CREATE_STACK_CANCEL";

export const CREATE_STACK_CONFIRM = "CREATE_STACK_CONFIRM";

export const DASHBOARD_CANCEL = "DASHBOARD_CANCEL";

export const DASHBOARD_CLEAR = "DASHBOARD_CLEAR";

export const DASHBOARD_RECEIVE = "DASHBOARD_RECEIVE";

export const DASHBOARD_REFRESH = "DASHBOARD_REFRESH";

export const DASHBOARD_REQUEST = "DASHBOARD_REQUEST";

export const DELETE_STACK = "DELETE_STACK";

export const DELETE_STACK_CANCEL = "DELETE_STACK_CANCEL";

export const DELETE_STACK_CONFIRM = "DELETE_STACK_CONFIRM";

export const LOAD_STACK = "LOAD_STACK"

export const REDIRECT = "REDIRECT";

export const REDIRECT_CLEAR = "REDIRECT_CLEAR";

export const STACK_REQUEST = "STACK_REQUEST";

export const STACK_RECEIVE = "STACK_RECEIVE";

export const TUTORIAL_DISMISS = "TUTORIAL_DISMISS";

export const TUTORIAL_RESET = "TUTORIAL_RESET";

export const UPDATE_STACK = "UPDATE_STACK";

export const UPDATE_STACK_CANCEL = "UPDATE_STACK_CANCEL";

export const UPDATE_STACK_CONFIRM = "UPDATE_STACK_CONFIRM";